### ISSUE TITLE
Multiple Folder Structure Sets

### ISSUE THREAD

**Issue by BlenderDefender** [BlenderDefender/blender_pm#14]
**Is your feature request related to a problem? Please describe.**
When I'm making projects for myself, I have another folder structure than for my videos. Both contain multiple Folders, so using the Custom Folders Option is not very great.

**Describe the solution you'd like**
I'd like to choose from multiple automatic folder presets.

**Comment by STeinWi** [comment]
Hi, 
I hope it's the right place, i'd like to report an installation problem.
Here the msg i get why trying to activate the addon : 

Traceback (most recent call last):
  File "C:\3D\Blender Launcher\stable\blender-2.91.2-windows64\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'blender_project_manager-1'

I tried with a 2.91.2 install and a fresh 2.93 alpha install.  (also with local install with the "config" directory in the "2.93" one)
Hope that help. 
In any case, thank you for making this addon, It reminded me of when i was using the old softimage XSI which had a project manager too.

**Comment by Larry3d** [comment]
![grafik](https://user-images.githubusercontent.com/38502179/108857793-5b9d6600-75e3-11eb-9f4c-64e28144bd67.png)
Unfortunately I have the same problem.

**Comment by BlenderDefender** [comment]
> 
> 
> ![grafik](https://user-images.githubusercontent.com/38502179/108857793-5b9d6600-75e3-11eb-9f4c-64e28144bd67.png)
> Unfortunately I have the same problem.

This seems to be a very common problem, I'll make a troubleshooting guide soon, over in the discussions page. The answer is: Unzip >> Remove "-1" from the Folder Name >> Zip >> Install.
