### ISSUE TITLE
Open Finder

### ISSUE THREAD

**Issue by stareagle** [BlenderDefender/blender_pm#16]
The addon works in macOS very well and the only issue I have had is that after you click the "build project" button, Finder isn't automatically loaded like explorer is in Win10. Is there a way to include a toggle to indicate which OS is being used and execute the appropriate code?

**Comment by BlenderDefender** [comment]
There is, I've tried to implement a solution for Mac OS, but unfortunately, I can't test it, because I have no Mac OS device. So the problem is not the toggle, the problem is that I don't know what the appropriate code for Mac OS is. If you can find a Developer using Mac OS, he may work on this. Till then, I guess I can't do anything about this issue, I'm sorry.

**Comment by stareagle** [comment]
I have a fix. In the main functions script replace the existing code for Darwin with subprocess.cal(["open", path"]). Ive tested this and it is working. Please take a look and if you need any macOS help please let me know.

**Comment by BlenderDefender** [comment]
Ok, I'll do this and I'll let you know if I need help with MacOS

**Comment by BlenderDefender** [comment]
Created a pull request, could you Test this on your device?

**Comment by stareagle** [comment]
Hi

OK dumb question, what do I do with a Pull Request. Git and I are not all that acquainted really sorry to say.

Stareagle

**Comment by BlenderDefender** [comment]
Well, here's the download link: https://github.com/BlenderDefender/blender_pm/archive/open_finder.zip

**Comment by BlenderDefender** [comment]
The pull request just means that I created a separate branch, so I don't mess up the main code in case I do something wrong

**Comment by stareagle** [comment]
Ah right now I get it. I must do a tutorial on GIT sometime. I do python coding for work and its something I really should do.

I installed the file you linked to and it works just fine…Good feeling having a fix of mine submitted

Cheers
Stareagle

**Comment by BlenderDefender** [comment]
I learned Git with [this free course](https://stude.co/1011322/git-tutorial-for-beginners), and I'm glad I did it. The accent is a bit strong, but you can still understand him without problems.
