### ISSUE TITLE
ModuleNotFoundError: No module named 'blender_project_manager-1'

### ISSUE THREAD

**Issue by farcaller** [BlenderDefender/blender_pm#19]
**Describe the bug**

Fresh install, fails to enable the module: the error is:
```
Traceback (most recent call last):
  File "C:\ProgramData\scoop\apps\blender\current\2.91\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'blender_project_manager-1'
```

**To Reproduce**
Download the module and try enabling it

**Desktop (please complete the following information):**
 - OS: Windows
 - Blender Version 2.91

**Comment by BlenderDefender** [comment]
https://github.com/BlenderDefender/blender_pm/issues/15

**Comment by BlenderDefender** [comment]
You have to unzip the folder, remove the "-1" suffix from the folder name (blender_project_manager-1) and zip it again. For some reason, if addon folders have names like this, Blender throws an error. I hope that helps, in case it doesn't, try to download it from the [Releases Page](https://github.com/BlenderDefender/blender_project_manager/releases)

Greetings,
Blender Defender
